### ISSUE TITLE
erreur dans la partie admin

### ISSUE THREAD

**Issue by jlandure** [SII-Nantes/callForPaper#12]
sur l'url `/api/admin/session`

```
<datastore-index kind="AdminRate" ancestor="false" source="manual">
        <property name="rowId" direction="asc"/>
        <property name="rate" direction="desc"/>
    </datastore-index>


	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:59)
	at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:119)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:96)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:76)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:36)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.getIndexList(BaseQueryResultsSource.java:152)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:181)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:164)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.ensureLoaded(QueryResultIteratorImpl.java:147)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.hasNext(QueryResultIteratorImpl.java:64)
	at com.google.appengine.datanucleus.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:54)
	at com.google.appengine.datanucleus.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:50)
	at com.google.appengine.datanucleus.query.QueryExceptionWrappers$1.get(QueryExceptionWrappers.java:49)
	at com.google.appengine.datanucleus.query.QueryExceptionWrappers$2.get(QueryExceptionWrappers.java:68)
	at com.google.appengine.datanucleus.query.RuntimeExceptionWrappingIterator.hasNext(RuntimeExceptionWrappingIterator.java:103)
	at com.google.appengine.datanucleus.query.LazyResult.listIterator(LazyResult.java:107)
	at com.google.appengine.datanucleus.query.StreamingQueryResult.iterator(StreamingQueryResult.java:141)
	at fr.sii.service.admin.rate.AdminRateService.matchUsers(AdminRateService.java:32)
	at fr.sii.service.admin.rate.AdminRateService.findByRowId(AdminRateService.java:104)
	at fr.sii.service.spreadsheet.SpreadsheetService.matchRates(SpreadsheetService.java:62)
	at fr.sii.service.spreadsheet.SpreadsheetService.getRowsSession(SpreadsheetService.java:135)
```

**Comment by jlandure** [comment]
Console admin : You have not created indexes for this application.
c'est normal ?

**Comment by jlandure** [comment]
@Thom-x  il faut que tu commit le fichier `WEB-INF/datastore-indexes.xml` ...

**Comment by Thom-x** [comment]
J'ai pas ce fichier dans mes sources. D'ailleurs j'ai jamais eu cette exception, étrange...

**Comment by Thom-x** [comment]
Quand je déploie j'ai ça :

```
Infos: Successfully processed E:\call-for-paper\target\call-for-paper-1.0-SNAPSHOT\WEB-INF\appengine-generated\datastore-indexes-auto.xml`
```

**Comment by jlandure** [comment]
Ok Thomas. Il faudrait que tu suive la formation appengine que je donne côté Zenika alors :rocket: 
`...`
Bref, le fichier est généré dès que tu démarre ton appli sur ton poste. Par contre vu qu'on utilise codeship, il ne l'a pas.
Peux-tu transférer ce fichier `datastore-indexes-auto.xml` dans le répertoire `WEB-INF` que tu commit ?

**Comment by Thom-x** [comment]
Je fais ça, j'ai lu la doc, maintenant je comprends ...

**Comment by Thom-x** [comment]
J'ai commit le fichier, dit moi si ça fonctionne (vu que mon appli a déjà les indexes) : d307ae7b178db267c9f6bee39bcc403d609fb9b3

**Comment by jlandure** [comment]
waip mais faut que je remerge :p

Le mer. 10 juin 2015 à 14:08, MAUGIN Thomas <notifications@github.com> a
écrit :
